base_config:
  - ../sr_base.yaml
  - ../earth_data.yaml
trainer_cls: tasks.rrdb.RRDBEarthDataTask
# model
hidden_size: 32
lr: 0.0002
num_block: 8

# train and eval
max_updates: 100000
batch_size: 32
eval_batch_size: 20
valid_steps: 3
